apiVersion: v1
kind: Pod
metadata:
  name: flaskpod
  labels:
    app: skawjdgns-flaskpod
spec:
  containers:
    - name: flask
      image: skawjdgns12/flaskapp:v1.0.0
      ports:
        - containerPort: 5000
  imagePullSecrets:
    - name: myregistrykey
